### ISSUE TITLE
Failed to load model class 'ReactModel' from module '@widgetti/jupyter-react'

### ISSUE THREAD

**Issue by fb-elong** [machow/reactable-py#45]
While opening an html file building from quarto for reactable, I got message below and the output table did not display.

The environment I had is within a company proxy. Is there a way to embed the module to make the report self contain? 

```
[Open Browser Console for more detailed log - Double click to close this message]
Failed to load model class 'ReactModel' from module '@widgetti/jupyter-react'
Error: Script error for "@widgetti/jupyter-react"
```

**Comment by fb-elong** [comment]
The root cause is 

1. the javascript https://cdn.jsdelivr.net/npm/@widgetti/jupyter-react@0.5.0/dist/index.js is missing. 
2. the source code `index.js` requires `https://ga.jspm.io/npm:es-module-shims@1.7.0/dist/es-module-shims.js` but is not accessible because it is not in white list. 

I am able to create an adhoc to fix it after I save the `index.js` as a local file and replace the `es-module-shims.js` link to use `https://cdn.jsdelivr.net/npm/es-module-shims@2.0.10/dist/es-module-shims.js` 

Then manually include the js file in header in quarto using 

```
format:
  html:
    include-in-header:
        - text: |
              <script src="/path/to/@widgetti/jupyter-react.js"></script>
```
